config/routes.rb
Rails.application.routes.draw do
  root 'types#index'

  get 'lists/show_lists'
  get 'lists/new_items'

  get 'lists/index'
    post 'lists/index'
  get 'lists/new'
  resources :types
  resources :lists

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :type, :class_name => Type, :foreign_key => "type_id"
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def show_lists
   @types_id = Type.find(params[:id])
    type = Type.find(@types_id)
    @lists = type.lists
    @lists = where(@types_id)
  end
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    #@lists = @type.lists
  end
#url_for(controller: 'lists_item', action: new_lists, id: type_id)
  def new_list
    @lists = List.new
    @types_id = Type.find(params[:id])
    @lists.type_id = @types_id
  end
  # GET /lists/1
  # GET /lists/1.json
  def show
    @lists = List.find(params[:id])
  end

  def addIdValue
    @type = Type.find(params[:id])

  end

  # GET /lists/new
  def new
    #@lists = List.find(params[:id])
    @types = Type.find_by_id(params[:id])
    #@lists.type_id = @types_id
    @lists = List.new
    @lists.type_id = @types
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    # @type = Type.new(type_params)
    #@type = Type.find(params[:id])
    @types = Type.find_by_id(params[:type_id])
    @lists = List.new(list_params)

    respond_to do |format|
      if @lists.save
        format.html { redirect_to @lists, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @lists }
      else
        format.html { render :new }
        format.json { render json: @lists.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @lists.update(list_params)
        format.html { redirect_to @lists, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @lists }
      else
        format.html { render :edit }
        format.json { render json: @lists.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @lists.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @lists = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :quantity, :type_id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @types = Type.find(params[:id])
    #@lists = @types.lists.find(params[:id])
    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @types }
    end
    redirect_to  url_for(controller: 'lists', :action => index, id: :id)
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to :action=>"index", notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:title, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingList2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @lists do |f| %>
   <% if @lists.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@lists.errors.count, "error") %> prohibited this type from being saved:</h2>

          <ul>
            <% @lists.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
 <!-- <%= debug @type %>-->
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @lists %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.quantity %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%-# <%= render 'form' -%>
<br>

<%= link_to 'New List', new_list_path %>
<%= link_to 'Back', root_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lists.name %>
</p>
<p>
  <strong>Title:</strong>
  <%= @lists.type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @lists.quantity %>
</p>

<%= link_to 'Edit', edit_list_path(@lists) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/show_lists.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lists.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @lists.quantity %>
</p>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Types</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= link_to type.id, type_path(type)%></td>
        <td><%= type.title %></td>
        <td><%= link_to 'Show', url_for(controller: 'lists', action: 'index', id: :id) %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @type.title %>
</p>

<div>
  <% @type.each do |types|%>
     <p> <%= types.name %></p>
     <p> <%= types.quantity %> </p>
  <% end %>

 <%= render 'form' %>

</div>
<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>